runtime: nodejs
env: flex
service: default
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 15
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
beta_settings:
  cloud_sql_instances: parachut-216816:us-central1:parachut
env_variables:
  ENVIRONMENT: 'production'
  FOREST_ENV_SECRET: '9b777c40ceac1cc14e584d5f451a6b804ac03fe8bb5f8f0dd2316d8db72bfe3f'
  FOREST_AUTH_SECRET: '6905e36ad4ffc24959181f3eaf207c225b6616b30369bb43'
  MONGO_URI: 'mongodb+srv://G267MnFEGDeByfok69Rvi6oF7F4zMy2Xg6jwGnp:sq9qWv7AQxKh2XqMiFWyE2y2Wiaw24H4f7naj9W@parachut-kto6u.mongodb.net/icarus-dev?retryWrites=true&w=majority'
  AUTHY: 'LZLONmSuGEvnQuXXsgh1tgnfX1PMgmga'
  EASYPOST: 'EZAK7e963085089645efb0963d479e326bbc6bsxvOT2Qvuki9v7y625tg'
  EASYPOST_CARRIER_ACCOUNT: 'ca_bd2f1d92ae7b45c79a92a1ae82f67327'
  SLACK_TOKEN: 'xoxp-106726056166-186119144690-566227669445-33e86bb6dc82a408a26b28985b2a5c4b'
  FRONT_SECRET: '4dce622a31e114be739556e3edfc6d37'
  FRONT_JWT_TOKEN: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZXMiOlsic2hhcmVkOioiLCJwcml2YXRlOioiXSwiaXNzIjoiZnJvbnQiLCJzdWIiOiJwYXJhY2h1dCJ9.Z0qTzMxIxg443FX4opxiAo4ai5vOLPWHKbjG_ksMqRc'
  FRONT_CHAT_SECRET: 'c86b4e008a84cc0710b878226db17185'
  GOOGLE_APPLICATION_CREDENTIALS: './gcloud.json'
  DAILY_RATE_PERCENT_MAX: '60'
  DAILY_RATE_PERCENT_MIN: '25'
  INSURANCE_PERCENT: '15'
  CONTRIBUTOR_PERCENT: '6'
  STRIPE: 'sk_test_vHRLsZ8cBjNcRL7JJOliTwbe00i0vt7UXf'
  PLAID_ID: '5c4b5c567ba2dd00119960f5'
  PLAID_PUBLIC_KEY: 'ffc78bac76ae7db8732758381376d4'
  PLAID_SECRET: 'a41dfcf2ce725290a362e7d8a18d25'
  POSTMARK: '5b1665ba-65be-47da-8bb7-59712fd9a088'
  SEGMENT: 'Wyl6CWXedZLKsaCZdeqOjVfUpAOXorxK'
  REDIS_HOST: '10.0.0.4'
  REDIS_PORT: '6379'
  SQL_USER: 'development'
  SQL_PASSWORD: 'pDzgvREbpiFVBjEEzNxw2Z48chmrHDN'
  SQL_DATABASE: 'development'
  INSTANCE_CONNECTION_NAME: 'parachut-216816:us-central1:parachut'
  ENGINE_API_KEY: 'service:brahms:B9TzHYzlQZx0D7aE_izljg'
  IPSTACK: '3935fe0faf46702950a3e4d4cf562c66'
  CLEARBIT: 'sk_a62b5564de8c0b4bc6aed20fee6afdc0'
  GEOCODIO: '9bd7121651459acb7d40064b2cd6dd95c79270d'
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
network:
  session_affinity: true
